import './globals.css'
import type { ReactNode } from 'react'
import Header  from '@/components/organisms/Header/Header'
import Footer  from '@/components/organisms/Footer/Footer'


export const metadata = {
	title: 'My App',
	description: 'Generated by Next.js',
}

type Props = {
	children: ReactNode
}

export default function RootLayout({ children }: Props) {
	return (
		<html lang="ja">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
